        *************** Beginning of data *************************************
0001.00              PGM                                                       
0002.00  /*                                                      */            
0003.00              DCL VAR(&JOB) TYPE(*CHAR) LEN(10)                         
0004.00              DCL VAR(&ALFA) TYPE(*CHAR) LEN(10)                        
0005.00              DCL VAR(&USER) TYYPE(*CHAR) LEN(10)                       
0006.00              RTVJOBA    JOB(&JOB) USER(&USER)                          
0007.00              ENDPGM                                                    
        ****************** End of data ****************************************