        *************** Beginning of data *************************************
0001.00 /*  PROGRAMA PRACTICA - HOLA MUNDO   */                                
0002.00 /*  AKIN A. RAMIREZ                  */                                
0003.00 /*                                   */                                
0004.00              PGM                                                       
0005.00              SNDMSG     MSG('Hola mundo Akin') TOUSR(AARG)             
0006.00              ENDPGM                                                    
        ****************** End of data ****************************************